title: Green Purity Test
description: The Green Purity Test serves to track how sustainable your lifestyle is. Click on every item you do.
url: "https://acgreenpuritytest.com"    # your custom domain

